import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import BottomNavbar from "@/components/navbar";

const ubuntu = Ubuntu({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudySpotter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col h-full ${ubuntu.className} items-center justify-center`}
      >
        <div className="flex-1 mb-40">{children}</div>
        <div className="flex items-center justify-center">
          <BottomNavbar />
        </div>
      </body>
    </html>
  );
}
